import React, { useState } from 'react';
import {
  FileBadge,
  Printer,
  Copy,
  Check,
  Building,
  User,
  AlertTriangle,
  HelpCircle,
  ShieldAlert,
  Calendar,
  Clock,
  ArrowRight,
  Download,
  FolderCheck,
  CheckSquare,
} from 'lucide-react';
import { DocumentAnalysis } from '../types';

interface LawyerBriefModalProps {
  analysis: DocumentAnalysis;
  onBackToWorkspace: () => void;
}

export const LawyerBriefModal: React.FC<LawyerBriefModalProps> = ({
  analysis,
  onBackToWorkspace,
}) => {
  const [userNotes, setUserNotes] = useState(
    'Meeting scheduled with legal counsel. Primary objectives: reduce liability exposure, push IP transfer to full payment date, and remove post-termination restraint.'
  );
  const [copied, setCopied] = useState(false);

  const lawyerQuestions: string[] =
    analysis.questionsForLawyer && analysis.questionsForLawyer.length > 0
      ? analysis.questionsForLawyer.flatMap((group) => group.questions.map((q) => q.question))
      : [
          'How can we amend Section 4.1 so that copyright and IP transfer to the client ONLY upon receipt of full payment?',
          'What standard language should we use to limit my total liability to the fees received (₹50,000)?',
          'Is the 12-month post-termination non-compete enforceable in our jurisdiction (e.g. under Section 27 of Indian Contract Act)?',
          'Can we remove the 90-day penalty holiday in Section 2.3 and replace it with 1.5% interest after 30 days?',
        ];

  const generateBriefingString = () => {
    return `=====================================================
LEXILENS ATTORNEY BRIEFING DOSSIER
Prepared for Legal Consultation
Generated: ${new Date().toLocaleDateString()}
Document: ${analysis.documentTitle}
=====================================================

1. DOCUMENT OVERVIEW & KEY FACTS
---------------------------------
Title: ${analysis.documentTitle}
Document Type: ${analysis.documentType}
Parties:
- ${analysis.parties[0]?.name} (${analysis.parties[0]?.shortLabel} - ${analysis.parties[0]?.role})
- ${analysis.parties[1]?.name} (${analysis.parties[1]?.shortLabel} - ${analysis.parties[1]?.role})
Core Purpose: ${analysis.whatThisDocumentDoes}
Jurisdiction: ${analysis.jurisdiction === 'india' ? 'India' : analysis.jurisdiction.toUpperCase()}

2. EXECUTIVE & PLAIN-ENGLISH SUMMARY
-------------------------------------
${analysis.executiveSummary}

3. IMPORTANT CLAUSES & COMMITMENTS
-----------------------------------
${analysis.parties[0]?.shortLabel || 'Party A'}:
${analysis.partyAObligations.map((o) => `* [${o.sectionRef}] ${o.title}: ${o.obligation} (Deadline: ${o.deadline || 'N/A'})`).join('\n')}

${analysis.parties[1]?.shortLabel || 'Party B'}:
${analysis.partyBObligations.map((o) => `* [${o.sectionRef}] ${o.title}: ${o.obligation} (Deadline: ${o.deadline || 'N/A'})`).join('\n')}

4. IDENTIFIED CONCERNS & ONE-SIDED PROVISIONS
---------------------------------------------
${analysis.potentialIssues
  .map(
    (issue, i) =>
      `${i + 1}. [${issue.location}] ${issue.title} (${issue.findingType})\n   Description: ${issue.description}\n   Why It Matters: ${issue.whyItMatters}\n   Suggested Question: ${issue.suggestedQuestion || 'N/A'}`
  )
  .join('\n\n')}

5. MISSING OR UNADDRESSED TERMS
--------------------------------
${analysis.missingInformation.map((m, i) => `* ${m}`).join('\n')}

6. RECOMMENDED QUESTIONS TO ASK LEGAL COUNSEL
---------------------------------------------
${lawyerQuestions.map((q, i) => `${i + 1}. ${q}`).join('\n')}

7. DOCUMENTS & EXHIBITS TO BRING TO CONSULTATION
------------------------------------------------
* Executed or draft copy of ${analysis.documentTitle}
* Statement of Work / technical specification appendices
* Written milestone submission records and email approvals
* Outstanding and paid invoice records
* Corporate / entity registration credentials

8. CLIENT CONSULTATION NOTES & OBJECTIVES
------------------------------------------
${userNotes}

=====================================================
MANDATORY ETHICAL DISCLAIMER:
This summary was generated by LexiLens to assist in organizing thoughts and documents prior to formal consultation. It does not constitute legal analysis, representation, or legal advice. Consult a licensed legal professional for binding advice.
=====================================================`;
  };

  const handleCopyBrief = () => {
    const briefText = generateBriefingString();
    navigator.clipboard.writeText(briefText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadDossier = () => {
    const briefText = generateBriefingString();
    const blob = new Blob([briefText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `LexiLens_Attorney_Brief_${analysis.documentTitle.replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 space-y-6 print:m-0 print:p-0">
      {/* Top Action Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200 print:hidden">
        <button
          onClick={onBackToWorkspace}
          className="text-xs text-slate-600 hover:text-slate-900 font-medium flex items-center gap-1 transition-colors cursor-pointer"
        >
          <span>← Back to Analysis Workspace</span>
        </button>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handleDownloadDossier}
            className="px-3.5 py-1.5 rounded-lg bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 text-xs font-medium flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs"
            title="Download complete dossier as text file"
          >
            <Download className="w-3.5 h-3.5 text-slate-500" />
            <span>Download .TXT</span>
          </button>
          <button
            onClick={handleCopyBrief}
            className="px-3.5 py-1.5 rounded-lg bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 text-xs font-medium flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
            <span>Copy Briefing Text</span>
          </button>
          <button
            onClick={handlePrint}
            className="px-4 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-white text-xs font-medium flex items-center gap-1.5 shadow-xs transition-colors cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>

      {/* Printable Briefing Document Canvas */}
      <div className="bg-white border border-slate-200 rounded-xl p-6 sm:p-10 space-y-8 shadow-xs print:bg-white print:text-black print:border-none print:shadow-none print:p-0">
        {/* Document Header */}
        <div className="border-b border-slate-200 pb-6 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">
              Attorney Consultation Brief
            </span>
            <span className="text-xs text-slate-500 font-mono">
              Date: {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
            </span>
          </div>
          <h1 className="text-2xl font-bold text-slate-900 font-sans tracking-tight">
            Legal Briefing Sheet: {analysis.documentTitle}
          </h1>
          <p className="text-xs text-slate-600 leading-relaxed">
            Organized review sheet designed for discussions with an attorney, summarizing responsibilities, warning signs, deadlines, required exhibits, and prioritized negotiation inquiries.
          </p>
        </div>

        {/* 1. Document Overview */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <span className="w-5 h-5 rounded bg-slate-100 text-slate-700 border border-slate-200 flex items-center justify-center text-[10px] font-bold">
              1
            </span>
            <span>Document Overview & Key Facts</span>
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
              <span className="text-[10px] uppercase font-semibold text-slate-500 block">
                Basic Details
              </span>
              <div className="text-xs space-y-1">
                <p><strong className="text-slate-800">Title:</strong> <span className="text-slate-700">{analysis.documentTitle}</span></p>
                <p><strong className="text-slate-800">Type:</strong> <span className="text-slate-700">{analysis.documentType}</span></p>
                <p><strong className="text-slate-800">Purpose:</strong> <span className="text-slate-700">{analysis.whatThisDocumentDoes}</span></p>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
              <span className="text-[10px] uppercase font-semibold text-slate-500 block">
                Parties Involved
              </span>
              <div className="text-xs space-y-2">
                {analysis.parties.map((p, i) => (
                  <div key={i} className="flex items-center gap-2">
                    {i === 0 ? <Building className="w-3.5 h-3.5 text-slate-600" /> : <User className="w-3.5 h-3.5 text-slate-600" />}
                    <span>
                      <strong className="text-slate-800">{p.name}</strong> ({p.role} - <span className="text-slate-600 font-medium">{p.shortLabel}</span>)
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* 2. Executive Summary */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <span className="w-5 h-5 rounded bg-slate-100 text-slate-700 border border-slate-200 flex items-center justify-center text-[10px] font-bold">
              2
            </span>
            <span>Plain-English Summary</span>
          </h2>
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-700 leading-relaxed">
            {analysis.executiveSummary}
          </div>
        </div>

        {/* 3. Key Obligations Side-by-Side */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <span className="w-5 h-5 rounded bg-slate-100 text-slate-700 border border-slate-200 flex items-center justify-center text-[10px] font-bold">
              3
            </span>
            <span>Key Commitments</span>
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2.5">
              <h3 className="font-bold text-xs text-slate-900 border-b border-slate-200 pb-1.5">
                {analysis.parties[0]?.shortLabel || 'Party A'} Commitments
              </h3>
              <ul className="space-y-2 text-xs text-slate-700">
                {analysis.partyAObligations.map((o) => (
                  <li key={o.id} className="leading-relaxed">
                    <strong className="text-slate-900">{o.title}</strong> ({o.sectionRef}): {o.obligation}
                    {o.deadline && <span className="text-slate-500 block text-[11px] font-medium">Deadline: {o.deadline}</span>}
                  </li>
                ))}
              </ul>
            </div>

            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2.5">
              <h3 className="font-bold text-xs text-slate-900 border-b border-slate-200 pb-1.5">
                {analysis.parties[1]?.shortLabel || 'Party B'} Commitments
              </h3>
              <ul className="space-y-2 text-xs text-slate-700">
                {analysis.partyBObligations.map((o) => (
                  <li key={o.id} className="leading-relaxed">
                    <strong className="text-slate-900">{o.title}</strong> ({o.sectionRef}): {o.obligation}
                    {o.deadline && <span className="text-slate-500 block text-[11px] font-medium">Deadline: {o.deadline}</span>}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* 4. Identified Concerns & One-Sided Clauses */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <span className="w-5 h-5 rounded bg-rose-50 text-rose-700 border border-rose-200 flex items-center justify-center text-[10px] font-bold">
              4
            </span>
            <span>Identified Concerns & Imbalances</span>
          </h2>

          <div className="space-y-3">
            {analysis.potentialIssues.map((issue) => (
              <div
                key={issue.id}
                className="p-4 rounded-xl bg-white border border-slate-200 space-y-2 text-xs shadow-xs"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-rose-50 text-rose-800 border border-rose-200">
                      {issue.findingType}
                    </span>
                    <strong className="text-slate-900">{issue.title}</strong>
                  </div>
                  <span className="text-slate-500 text-[11px] font-medium">{issue.location}</span>
                </div>
                <p className="text-slate-700 leading-relaxed font-sans">{issue.description}</p>
                <p className="text-amber-800 bg-amber-50 p-2.5 rounded-lg border border-amber-200 text-xs leading-relaxed">
                  <strong>Why it matters:</strong> {issue.whyItMatters}
                </p>
                {issue.suggestedQuestion && (
                  <p className="text-slate-800 bg-slate-50 p-2.5 rounded-lg border border-slate-200 text-xs italic">
                    <strong>Recommended question for attorney:</strong> "{issue.suggestedQuestion}"
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* 5. Missing Information */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <span className="w-5 h-5 rounded bg-slate-100 text-slate-700 border border-slate-200 flex items-center justify-center text-[10px] font-bold">
              5
            </span>
            <span>Missing or Unclear Terms</span>
          </h2>

          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
            <ul className="space-y-1.5 text-xs text-slate-700 list-disc pl-5 marker:text-slate-400">
              {analysis.missingInformation.map((m, idx) => (
                <li key={idx} className="leading-relaxed">
                  {m}
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* 6. Specific Questions to Ask Legal Professional */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <span className="w-5 h-5 rounded bg-slate-100 text-slate-700 border border-slate-200 flex items-center justify-center text-[10px] font-bold">
              6
            </span>
            <span>Prioritized Questions for Your Attorney</span>
          </h2>

          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2.5">
            {lawyerQuestions.map((q, idx) => (
              <div key={idx} className="flex items-start gap-2 text-xs text-slate-800">
                <span className="font-bold text-slate-900 shrink-0">{idx + 1}.</span>
                <p className="leading-relaxed">{q}</p>
              </div>
            ))}
          </div>
        </div>

        {/* 7. Documents & Exhibits to Bring to Consultation (Requirement #7) */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <span className="w-5 h-5 rounded bg-slate-100 text-slate-700 border border-slate-200 flex items-center justify-center text-[10px] font-bold">
              7
            </span>
            <span>Documents & Exhibits to Bring</span>
          </h2>

          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
            <p className="text-xs text-slate-600 mb-2">
              Gather these supporting records before your consultation to give your attorney full context:
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-slate-800">
              <div className="flex items-start gap-2 p-2 bg-white rounded border border-slate-200">
                <FolderCheck className="w-4 h-4 text-[#1E3A8A] shrink-0 mt-0.5" />
                <span>Original executed or draft copy of <strong>{analysis.documentTitle}</strong></span>
              </div>
              <div className="flex items-start gap-2 p-2 bg-white rounded border border-slate-200">
                <FolderCheck className="w-4 h-4 text-[#1E3A8A] shrink-0 mt-0.5" />
                <span>Statement of Work (SOW) or deliverable specifications</span>
              </div>
              <div className="flex items-start gap-2 p-2 bg-white rounded border border-slate-200">
                <FolderCheck className="w-4 h-4 text-[#1E3A8A] shrink-0 mt-0.5" />
                <span>Email correspondence detailing milestone approvals or changes</span>
              </div>
              <div className="flex items-start gap-2 p-2 bg-white rounded border border-slate-200">
                <FolderCheck className="w-4 h-4 text-[#1E3A8A] shrink-0 mt-0.5" />
                <span>Invoices submitted to date and payment receipts</span>
              </div>
            </div>
          </div>
        </div>

        {/* 8. Client Notes & Consultation Objectives */}
        <div className="space-y-3 print:hidden">
          <h2 className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <span className="w-5 h-5 rounded bg-slate-100 text-slate-700 border border-slate-200 flex items-center justify-center text-[10px] font-bold">
              8
            </span>
            <span>Your Personal Notes & Objectives</span>
          </h2>
          <textarea
            value={userNotes}
            onChange={(e) => setUserNotes(e.target.value)}
            rows={3}
            placeholder="Type specific discussion points or client goals for your meeting with legal counsel..."
            className="w-full p-3.5 bg-white border border-slate-300 rounded-xl text-xs text-slate-800 focus:outline-none focus:border-slate-500 leading-relaxed font-sans shadow-xs"
          />
        </div>

        {/* 9. Mandatory Legal Disclaimer */}
        <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-600 space-y-1">
          <span className="font-bold text-slate-800 uppercase flex items-center gap-1.5">
            <ShieldAlert className="w-4 h-4 text-slate-700" />
            Important Disclaimer
          </span>
          <p className="leading-relaxed">
            This summary was generated by LexiLens to help organize documents and questions prior to a consultation. It does not constitute formal legal representation or binding legal advice. Always consult a licensed attorney in your jurisdiction.
          </p>
        </div>
      </div>
    </div>
  );
};
